name: 'Quality Gate Action'
description: 'Valida se um arquivo existe e realiza checks de qualidade'
inputs:
  requiredFile:
    description: 'Nome do arquivo necessário para o build'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  